version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: "/sonarcloud/token"

phases:
  install:
    runtime-versions:
      java: corretto21  # This explicitly tells AWS CodeBuild to set up Java 21
  build:
    commands:
      - echo "Starting Java 21 environment confirmation..."
      - java -version
      - echo "Starting SonarCloud Quality Gate Scan..."
      - >
        mvn verify sonar:sonar
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=by292929
        -Dsonar.projectKey=By292929_spring-webapp-main
        -Dsonar.login=$SONAR_TOKEN
        -Dsonar.qualitygate.wait=true
artifacts:
  files:
    - '**/*'
