version: 0.2
phases:
  build:
    commands:
      - ./mvnw clean package
      - docker build -t $REPO_URI:latest .
  post_build:
    commands:
      - docker push $REPO_URI:latest
      - printf '{"ImageURI":"%s"}' $REPO_URI:latest > imageDetail.json
artifacts:
  files:
    - imageDetail.json
    - service-stack.yaml
    - appspec.yaml    # Needed for Blue/Green
    - taskdef.json    # Needed for Blue/Green
