version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: "/sonarcloud/token"

phases:
  build:
    commands:
      - echo "Starting SonarCloud Quality Gate Scan..."
      - >
        mvn verify sonar:sonar
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=by292929
        -Dsonar.projectKey=By292929_spring-webapp-main
        -Dsonar.login=$SONAR_TOKEN
        -Dsonar.qualitygate.wait=true
artifacts:
  files:
    - '**/*'
