version: 0.2
phases:
  build:
    commands:
      - ./mvnw clean package
      - docker build -t $REPO_URI:latest .
  post_build:
    commands:
      - docker push $REPO_URI:latest
      # 1. Create the image metadata for ECS
      - printf '{"ImageURI":"%s"}' $REPO_URI:latest > imageDetail.json
      # 2. UPLOAD the nested template to S3 (Crucial for Nested Stacks)
      - aws s3 cp service-stack.yaml s3://$TEMPLATE_BUCKET/templates/service-stack.yaml
artifacts:
  files:
    - imageDetail.json
    - service-stack.yaml
    - appspec.yaml
    - taskdef.json
