version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 392785071161.dkr.ecr.ap-southeast-1.amazonaws.com
      
  build:
    commands:
      - docker build -t spring-app:latest .

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker tag spring-app:latest $SPRING_ECR_URL:latest
      - docker push $SPRING_ECR_URL:latest
      - printf '{"ImageURI":"%s"}' "$SPRING_ECR_URL:latest" > imageDetail.json
      - aws s3 cp service-stack.yaml s3://codepipeline-ap-southeast-1-32e8a53442fb-4755-93f9-92936e8733f6/templates/service-stack.yaml

artifacts:
  files:
    - imageDetail.json
    - service-stack.yaml
    - appspec.yaml
