AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId: {Type: String}
  SubnetA: {Type: String}
  SubnetB: {Type: String}
  ClusterName: {Type: String}
  ImageURI: {Type: String}
  ExecutionRoleArn: {Type: String}
  SecurityGroupId: {Type: String}
  TargetGroupArn:
    Type: String

Resources:
  SpringTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: spring-webapp
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref ExecutionRoleArn
      ContainerDefinitions:
        - Name: spring-app
          Image: !Ref ImageURI
          PortMappings: [{ContainerPort: 8080}]

  SpringService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: spring-webapp-service
      HealthCheckGracePeriodSeconds: 120
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref SpringTaskDef
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [!Ref SubnetA, !Ref SubnetB]
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref SecurityGroupId
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroupArn
          ContainerName: spring-app
          ContainerPort: 8080
